apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: many-apps-many-clusters
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              values:
                name: '{{name}}'  
          - git:
              repoURL: https://github.com/idanhoro/gitops-cert-level-2-examples.git
              revision: HEAD
              directories:
                - path: application-sets/example-apps/*
  template:
    metadata:
      name: '{{path.basename}}-{{values.name}}'  
    spec:
      project: default
      source:
        repoURL: https://github.com/idanhoro/gitops-cert-level-2-examples.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
